"""Regenerate the linked notation index from the reviewed notation.json."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
rows = json.loads((ROOT / "notation.json").read_text())
head = r"""% Generated by scripts/build_notation.py; edit notation.json.
\chapter*{Index of Notation}
\markboth{Index of Notation}{}
\addcontentsline{toc}{chapter}{Index of Notation}
Entries are grouped by the discussion in which the notation is introduced
or explained. Item numbers follow Warner; pages and links refer to this reprint.
Some symbols recur with different meanings in different chapters.

{\small\setlength{\tabcolsep}{3pt}\renewcommand{\arraystretch}{1.15}
\begin{longtable}{@{}>{\raggedright\arraybackslash}p{.39\linewidth}>{\raggedright\arraybackslash}p{.39\linewidth}r r@{}}
\toprule Symbol & Meaning & Item & Page\\\midrule\endfirsthead
\toprule Symbol & Meaning & Item & Page\\\midrule\endhead
\bottomrule\endfoot
"""
body = []
for row in rows:
    symbol = row["symbol"].replace(",", r",\allowbreak ")
    item = row["item"]
    body.append(symbol + " & " + row["meaning"]
                + rf" & \ref{{thm:{item}}} & \pageref{{thm:{item}}} \\")
(ROOT / "chapters/notation.tex").write_text(
    head + "\n".join(body) + "\n" + r"\end{longtable}}" + "\n")
print(f"Generated {len(rows)} linked notation entries.")
